version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:13.7

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  deploy:
    steps:
      - attach_workspace:
        at: ~/repo
      - run:
        name: Authenticate with repo
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
        name: Publish package
        command: yarn publish --minor

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
        requires:
          - test
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/